<html>
<head>
<title>test__issues461_471.py</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<style type="text/css">
.s0 { color: #629755; font-style: italic;}
.s1 { color: #a9b7c6;}
.s2 { color: #cc7832;}
.s3 { color: #6897bb;}
.s4 { color: #6a8759;}
.s5 { color: #808080;}
</style>
</head>
<body bgcolor="#2b2b2b">
<table CELLSPACING=0 CELLPADDING=5 COLS=1 WIDTH="100%" BGCOLOR="#606060" >
<tr><td><center>
<font face="Arial, Helvetica" color="#000000">
test__issues461_471.py</font>
</center></td></tr></table>
<pre><span class="s0">'''Test for GitHub issues 461 and 471. 
 
When moving to Python 3, handling of KeyboardInterrupt exceptions caused 
by a Ctrl-C raised an exception while printing the traceback for a 
greenlet preventing the process from exiting. This test tests for proper 
handling of KeyboardInterrupt. 
'''</span>

<span class="s2">import </span><span class="s1">sys</span>

<span class="s2">if </span><span class="s1">sys.argv[</span><span class="s3">1</span><span class="s1">:] == [</span><span class="s4">'subprocess'</span><span class="s1">]: </span><span class="s5"># pragma: no cover</span>
    <span class="s2">import </span><span class="s1">gevent</span>

    <span class="s2">def </span><span class="s1">task():</span>
        <span class="s1">sys.stdout.write(</span><span class="s4">'ready</span><span class="s2">\n</span><span class="s4">'</span><span class="s1">)</span>
        <span class="s1">sys.stdout.flush()</span>
        <span class="s1">gevent.sleep(</span><span class="s3">30</span><span class="s1">)</span>

    <span class="s2">try</span><span class="s1">:</span>
        <span class="s1">gevent.spawn(task).get()</span>
    <span class="s2">except </span><span class="s1">KeyboardInterrupt:</span>
        <span class="s2">pass</span>

    <span class="s1">sys.exit(</span><span class="s3">0</span><span class="s1">)</span>

<span class="s2">else</span><span class="s1">:</span>
    <span class="s2">import </span><span class="s1">signal</span>
    <span class="s2">from </span><span class="s1">subprocess </span><span class="s2">import </span><span class="s1">Popen</span><span class="s2">, </span><span class="s1">PIPE</span>
    <span class="s2">import </span><span class="s1">time</span>

    <span class="s2">import </span><span class="s1">unittest</span>
    <span class="s2">import </span><span class="s1">gevent.testing </span><span class="s2">as </span><span class="s1">greentest</span>
    <span class="s2">from </span><span class="s1">gevent.testing.sysinfo </span><span class="s2">import </span><span class="s1">CFFI_BACKEND</span>
    <span class="s2">from </span><span class="s1">gevent.testing.sysinfo </span><span class="s2">import </span><span class="s1">RUN_COVERAGE</span>
    <span class="s2">from </span><span class="s1">gevent.testing.sysinfo </span><span class="s2">import </span><span class="s1">WIN</span>
    <span class="s2">from </span><span class="s1">gevent.testing.sysinfo </span><span class="s2">import </span><span class="s1">PYPY3</span>

    <span class="s2">class </span><span class="s1">Test(unittest.TestCase):</span>

        <span class="s1">@unittest.skipIf(</span>
            <span class="s1">(CFFI_BACKEND </span><span class="s2">and </span><span class="s1">RUN_COVERAGE) </span><span class="s2">or </span><span class="s1">(PYPY3 </span><span class="s2">and </span><span class="s1">WIN)</span><span class="s2">,</span>
            <span class="s4">&quot;Interferes with the timing; times out waiting for the child&quot;</span><span class="s1">)</span>
        <span class="s2">def </span><span class="s1">test_hang(self):</span>
            <span class="s5"># XXX: Why does PyPy3 on Win fail to kill the child? (This was before we switched</span>
            <span class="s5"># to pypy3w; perhaps that makes a difference?)</span>
            <span class="s2">if </span><span class="s1">WIN:</span>
                <span class="s2">from </span><span class="s1">subprocess </span><span class="s2">import </span><span class="s1">CREATE_NEW_PROCESS_GROUP</span>
                <span class="s1">kwargs = {</span><span class="s4">'creationflags'</span><span class="s1">: CREATE_NEW_PROCESS_GROUP}</span>
            <span class="s2">else</span><span class="s1">:</span>
                <span class="s1">kwargs = {}</span>
            <span class="s5"># (not on Py2) pylint:disable=consider-using-with</span>
            <span class="s1">p = Popen([sys.executable</span><span class="s2">, </span><span class="s1">__file__</span><span class="s2">, </span><span class="s4">'subprocess'</span><span class="s1">]</span><span class="s2">, </span><span class="s1">stdout=PIPE</span><span class="s2">, </span><span class="s1">**kwargs)</span>
            <span class="s1">line = p.stdout.readline()</span>
            <span class="s2">if not </span><span class="s1">isinstance(line</span><span class="s2">, </span><span class="s1">str):</span>
                <span class="s1">line = line.decode(</span><span class="s4">'ascii'</span><span class="s1">)</span>
            <span class="s5"># Windows needs the \n in the string to write (because of buffering), but</span>
            <span class="s5"># because of newline handling it doesn't make it through the read; whereas</span>
            <span class="s5"># it does on other platforms. Universal newlines is broken on Py3, so the best</span>
            <span class="s5"># thing to do is to strip it</span>
            <span class="s1">line = line.strip()</span>
            <span class="s1">self.assertEqual(line</span><span class="s2">, </span><span class="s4">'ready'</span><span class="s1">)</span>
            <span class="s5"># On Windows, we have to send the CTRL_BREAK_EVENT (which seems to terminate the process); SIGINT triggers</span>
            <span class="s5"># &quot;ValueError: Unsupported signal: 2&quot;. The CTRL_C_EVENT is ignored on Python 3 (but not Python 2).</span>
            <span class="s5"># So this test doesn't test much on Windows.</span>
            <span class="s1">signal_to_send = signal.SIGINT </span><span class="s2">if not </span><span class="s1">WIN </span><span class="s2">else </span><span class="s1">getattr(signal</span><span class="s2">, </span><span class="s4">'CTRL_BREAK_EVENT'</span><span class="s1">)</span>
            <span class="s1">p.send_signal(signal_to_send)</span>
            <span class="s5"># Wait a few seconds for child process to die. Sometimes signal delivery is delayed</span>
            <span class="s5"># or even swallowed by Python, so send the signal a few more times if necessary</span>
            <span class="s1">wait_seconds = </span><span class="s3">25.0</span>
            <span class="s1">now = time.time()</span>
            <span class="s1">midtime = now + (wait_seconds / </span><span class="s3">2.0</span><span class="s1">)</span>
            <span class="s1">endtime = time.time() + wait_seconds</span>
            <span class="s2">while </span><span class="s1">time.time() &lt; endtime:</span>
                <span class="s2">if </span><span class="s1">p.poll() </span><span class="s2">is not None</span><span class="s1">:</span>
                    <span class="s2">break</span>
                <span class="s2">if </span><span class="s1">time.time() &gt; midtime:</span>
                    <span class="s1">p.send_signal(signal_to_send)</span>
                    <span class="s1">midtime = endtime + </span><span class="s3">1 </span><span class="s5"># only once</span>
                <span class="s1">time.sleep(</span><span class="s3">0.1</span><span class="s1">)</span>
            <span class="s2">else</span><span class="s1">:</span>
                <span class="s5"># Kill unresponsive child and exit with error 1</span>
                <span class="s1">p.terminate()</span>
                <span class="s1">p.wait()</span>
                <span class="s2">raise </span><span class="s1">AssertionError(</span><span class="s4">&quot;Failed to wait for child&quot;</span><span class="s1">)</span>

            <span class="s5"># If we get here, it's because we caused the process to exit; it</span>
            <span class="s5"># didn't hang. Under Windows, however, we have to use CTRL_BREAK_EVENT,</span>
            <span class="s5"># which has an arbitrary returncode depending on versions (so does CTRL_C_EVENT</span>
            <span class="s5"># on Python 2). We still</span>
            <span class="s5"># count this as success.</span>
            <span class="s1">self.assertEqual(p.returncode </span><span class="s2">if not </span><span class="s1">WIN </span><span class="s2">else </span><span class="s3">0</span><span class="s2">, </span><span class="s3">0</span><span class="s1">)</span>
            <span class="s1">p.stdout.close()</span>

    <span class="s2">if </span><span class="s1">__name__ == </span><span class="s4">'__main__'</span><span class="s1">:</span>
        <span class="s1">greentest.main()</span>
</pre>
</body>
</html>